<a href="https://colab.research.google.com/github/HaekyoungRho/DALC_Scala/blob/main/DALC_scalar4_%ED%8C%8C%EC%9D%B4%EC%8D%AC_%EB%8D%B0%EC%9D%B4%ED%84%B0_%ED%83%80%EC%9E%85%EA%B3%BC_numpy%EC%9D%B4%ED%95%B4%ED%95%98%EA%B8%B0__.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy 기초

## 넘파이 패키지 불러오기

In [19]:
# 넘파이 패키지를 불러오기 np로 줄여쓰기
import numpy as np

## array 정의 및 생성

In [20]:
# 넘파이 array를 사용하여 a라는 변수에 1부터 10까지의 숫자 리스트 배열을 생성하기
a = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10])
print(a)

[ 1  2  3  4  5  6  7  8  9 10]


In [21]:
#파이썬의 기본 range 함수와 비슷한 넘파이 range 함수를 사용하여 ndarray를 만들 수 있습니다:
ndarray =  np.array(range(20))
print(ndarray)

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19]


## 배열 구성

In [22]:
# full 함수를 사용하여 b라는 변수에 2.71 수로 3 X 4 다차원 배열 만들기
b = np.full((3,4), 2.71)
print(b)

[[2.71 2.71 2.71 2.71]
 [2.71 2.71 2.71 2.71]
 [2.71 2.71 2.71 2.71]]


In [23]:
# arrange 함수를 사용하여 c라는 변수에 0부터 10까지 짝수만 있는 배열 구성하기
c = np.arange(0,11,2)
print(c)

[ 0  2  4  6  8 10]


In [24]:
# linespace 함수를 사용하여 d라는 변수에 0부터 1까지 4개 요소 값을 가진 배열 생성하기
d = np.linspace(0, 1, 4)
print(d)

[0.         0.33333333 0.66666667 1.        ]


In [25]:
# randint 함수를 사용하여 0 부터 100까지 수를 2 X 2 배열로 생성하기
arr = np.random.randint(1, 100, size=(2, 2))
print(arr)

[[84 31]
 [75 57]]


## 배열 인덱싱

In [27]:
# a변수에서 인덱스 2 (앞에서 3번째) 와 인덱스 -3 (뒤에서 3번째)에 해당하는 수 가져오기
a[2]
a[-3]

8

In [29]:
# a 변수에서 인덱스 3부터 9 까지 슬라이싱하기
a[3:9]

array([4, 5, 6, 7, 8, 9])

## 배열 재구조화

In [31]:
#차원의 개수 알아보는 함수
b.ndim

2

In [35]:
#차원의 크기 알아보는 함수
a.shape

(10,)

In [36]:
#전체 배열크기 알아보는 함수
a.size

10

In [41]:
#0부터10까지 정수를 가진 x변수에서 4~7까지의 요소를 가진 하위배열생성
x = np.arange(0,11)
x1 = x[4:8]
x1

array([4, 5, 6, 7])

In [42]:
#0부터10까지 정수를 가진 x변수에서 첫번째 다섯 요소를 가진 하위 배열 생성
x[:5]

array([0, 1, 2, 3, 4])

In [43]:
#0부터10까지 정수를 가진 x변수에서 인덱스 5 이후의 요소를 가진 하위 배열을 생성
x[5:]

array([ 5,  6,  7,  8,  9, 10])

In [48]:
# 인덱스 0,1행과 인덱스 0,1,2열 즉 2행3열인 다차원 하위 배열 생성(콤마이용하기)
s = np.array([[4, 5, 6], [7, 8, 9]])
s

array([[4, 5, 6],
       [7, 8, 9]])

In [56]:
#1부터 10까지 배열을 3행3열로 재배열하기(reshape사용)
p =  np.arange(0,9)
p1 = p.reshape((3,3))
p1

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

## 배열 결합

In [57]:
#두개의 배열 결합하기
a = np.array([[1, 2], [3, 4]])
b = np.array([[7, 8], [9, 10], [11, 12]])

print(np.concatenate((a, b), axis=0))

[[ 1  2]
 [ 3  4]
 [ 7  8]
 [ 9 10]
 [11 12]]


In [59]:
#수직으로 두개의 배열 결합하기
c = np.vstack((a,b))
c

array([[ 1,  2],
       [ 3,  4],
       [ 7,  8],
       [ 9, 10],
       [11, 12]])

In [62]:
#수평으로 두개의 배열 결합하기
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])
d = np.hstack((a,b))
d

array([1, 2, 3, 4, 5, 6])

## 배열 분할

In [67]:
#7개의 숫자를 가진 리스트 x를 3개의 변수 x1,x2,x3로 분할하기
x1,x2,x3 = np.split(x, (3, 6))
x1,x2,x3

(array([0, 1, 2]), array([3, 4, 5]), array([ 6,  7,  8,  9, 10]))

In [74]:
#4행4열 차원을 배열이 상하 2개로 나누게 분할
q = np.arange(16)
q = q.reshape((4,4))
split1, split2=np.split(q,2,axis=0)
print(split1)
print(split2)

[[0 1 2 3]
 [4 5 6 7]]
[[ 8  9 10 11]
 [12 13 14 15]]


# Numpy 심화

## 유니버셜함수

In [75]:
# zeros 함수는 0으로 채워진 배열을 만듭니다:
np.zeros(5)

array([0., 0., 0., 0., 0.])

In [76]:
#2D 배열(즉, 행렬)을 만들려면 원하는 행과 열의 크기를 튜플로 전달합니다. 예를 들어 다음은 3 \times 4 크기의 행렬입니다:

np.zeros((3,4))

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [77]:
a = np.zeros((3,4))
a

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [79]:
a.shape

(3, 4)

In [78]:
a.ndim # len(a.shape)와 같습니다

2

In [80]:
a.size

12

In [81]:
# 초기화되지 않은 2 \times 3 크기의 배열을 만듭니다(배열의 내용은 예측이 불가능하며 메모리 상황에 따라 달라집니다):

np.empty((2,3))

array([[4.9e-324, 9.9e-324, 1.5e-323],
       [2.0e-323, 2.5e-323, 3.0e-323]])

In [82]:
#array 함수는 파이썬 리스트를 사용하여 ndarray를 초기화합니다:

np.array([[1,2,3,4], [10, 20, 30, 40]])

array([[ 1,  2,  3,  4],
       [10, 20, 30, 40]])

In [85]:
# x = np.array([-10, -5, 0, 3, 7])
# x에 있는 배열을 모두 양의 정수로 반환하기
x = np.absolute([-10, -5, 0, 3, 7])
x

array([10,  5,  0,  3,  7])

In [86]:
# 모두 양의 정수가 된 배열 x를 자연로그 배열로 반환하기
x10 = np.log(x)
x10

/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:2: RuntimeWarning: divide by zero encountered in log
  


array([2.30258509, 1.60943791,       -inf, 1.09861229, 1.94591015])

## 집계함수

In [89]:
x=np.array([-2,-1,0,1,2])
"절댓값을 씌우려면?"
힌트: "np.absolute(x)"
x = np.absolute(x)
x

array([2, 1, 0, 1, 2])

In [91]:
#삼각함수
theta = np.linspace(0,np.pi,3)
print("theta=" , theta)
a = np.cos(np.array([0, np.pi/2, np.pi]))
print(" 코사인 함수 =",a)
a = np.tan(np.array([-np.pi, np.pi/2, np.pi]))
print("탐젠트 함수= ", a) 

theta= [0.         1.57079633 3.14159265]
 코사인 함수 = [ 1.000000e+00  6.123234e-17 -1.000000e+00]
탐젠트 함수=  [ 1.22464680e-16  1.63312394e+16 -1.22464680e-16]


In [92]:
#역삼각함수
a = np.arcsin(1)
print("역 사인함수=",a)
a = np.arccos(1)  
print("역 코사인함수=",a)
a = np.arctan(0) 
print("역 탄젠트함수=",a)

역 사인함수= 1.5707963267948966
역 코사인함수= 0.0
역 탄젠트함수= 0.0


In [104]:
#로그함수
x=[1,2,4,10]
a = np.e
print("자연로그=",a)
print("밑이2인 로그함수=",np.log2(x))
print("밑이 10인 로그함수=",np.log10(x))

자연로그= 2.718281828459045
밑이2인 로그함수= [0.         1.         2.         3.32192809]
밑이 10인 로그함수= [0.         0.30103    0.60205999 1.        ]


In [106]:
#지수함수
x=[1,2,3]

print("e^x=",np.exp(x))
print("2^x",np.exp2(x))
print("3^x=",np.power(3, x))

e^x= [ 2.71828183  7.3890561  20.08553692]
2^x [2. 4. 8.]
3^x= [ 3  9 27]


In [107]:
#out 인자 
x=np.arange(5)
y=np.empty(5)
np.power(x,10,out=y)
print(y)

[0.000000e+00 1.000000e+00 1.024000e+03 5.904900e+04 1.048576e+06]


In [110]:
#out 인자를 활용하여 배열 슬라이싱
x=np.arange(5)
y=np.empty(10)
np.power(2,x,out=y[::2])
print(y)

[1.00000000e+000 6.79038653e-313 2.00000000e+000 6.79038653e-313
 4.00000000e+000 6.79038653e-313 8.00000000e+000 2.14321575e-312
 1.60000000e+001 0.00000000e+000]


In [111]:
#reduce 함수
x=np.arange(1,5)
np.add.reduce(x)

10

In [112]:
#sum,max,min함수
s=np.random.random(1000)
print("s의최솟값=",np.min(s))
print("s의최댓값=",np.max(s))


s의최솟값= 0.0005317806798643687
s의최댓값= 0.9993467443924876


In [ ]:
#axis 인자
"axis=0: 열기준 집계연산"
"axis=1: 행기준 집계연산"
"axis=none: 배열 내 모든 요소의 집계연산axis 인자"

In [115]:
m= np.random.random((3,4))
print(m)

[[0.88628205 0.50126244 0.96976144 0.55308634]
 [0.4698084  0.60726696 0.40759905 0.3208719 ]
 [0.98620103 0.15413201 0.02668444 0.9115303 ]]


## 브로드캐스팅 연산

In [120]:
# 크기가 같은 어레이의 연산을 하기
X= np.array([0,1,2]) 
M = np.array([3,4,5]) 
print(X+M)

[3 5 7]


In [130]:
# 배열의 크기를 늘려서 연산하기
X = np.array([0,1,2]) 
M = np.ones((3,3))
print(X + M)

[[1. 2. 3.]
 [1. 2. 3.]
 [1. 2. 3.]]


## 비교연산자

In [131]:
# any 함수를 이용하여 하나라도 만족하면 true를 산출하는 코드만들기
arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
np.any(arr > 5)

True

In [133]:
# all함수를 이용하여 true산출 코드 만들기
np.all(arr < 10)

True

In [146]:
# 1~5사이의 구간에서 5개 정수를 무작위로 발생시켜 1차원배열 2개변수를 생성하고 이에대한 불리언 값 결과내기
a = np.random.randint(1, 6, size=5)
b = np.random.randint(1, 6, size=5)
print(a, b)
a > b

[5 1 4 2 5] [5 4 4 2 1]


array([False, False, False, False,  True])

## 팬시 인덱싱

In [162]:
#배열을 생성하여 인덱싱하기
a = np.arange(10)
a

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [163]:
#인덱스 값을 가진 2차원 배열(예를 들어 row=np.array([0,1,2]))을 이용하여 인덱싱
b = np.array([3,6,9])
b

array([3, 6, 9])

## 정렬 

In [165]:
#np.sort함수를 이용하여 복사하기
a = np.random.randint(1, 6, size=5)
b = np.random.randint(1, 6, size=5)

a_sorted = np.sort(a)
a,a_sorted

(array([3, 1, 5, 5, 4]), array([1, 3, 4, 5, 5]))

In [167]:
#변수.sort함수를 이용하여 정렬하기
a.sort()
a

array([1, 3, 4, 5, 5])

In [169]:
#np.arsort함수 이용하여 정렬 요소의 인덱스를 반환하기
s = a.argsort()
s

array([1, 0, 3, 2])

In [170]:
#x_reverse를 이용하여 내림차순
x = np.array([4, 2, 6, 5, 1, 3, 0])
x_reverse = np.sort(x)[::-1]
x, x_reverse

(array([4, 2, 6, 5, 1, 3, 0]), array([6, 5, 4, 3, 2, 1, 0]))

In [175]:
#axis를 이용하여 각 열을 기준으로 정렬하기
a = np.array([[48, 52, 56, 60],[64, 68, 72, 76]])
np.sort(a, axis = 0)

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])

In [178]:
#axis를 이용하여 각 행을 기준으로 정렬하기#axis를 이용하여 각 행을 기준으로 정렬하기
a = np.array([[48, 52, 56, 60],[64, 68, 72, 76]])
np.sort(a, axis = 1)

array([[48, 52, 56, 60],
       [64, 68, 72, 76]])